# Generated by Django 4.2 on 2023-04-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_product_user_productscomments_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productscomments',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productscomments',
            old_name='comment',
            new_name='text',
        ),
    ]
