# Generated by Django 4.2 on 2023-05-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_product_id_productscomments_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscomments',
            name='stars',
            field=models.CharField(blank=True, choices=[('1', 'very bad'), ('2', 'bad'), ('3', 'normal'), ('4', 'good'), ('5', 'perfect')], max_length=10, verbose_name='Score of Product'),
        ),
        migrations.AlterField(
            model_name='productscomments',
            name='text',
            field=models.TextField(verbose_name='comment text'),
        ),
    ]
